/**
 * 单词生成工具
 * 使用简洁的数据结构生成500个单词
 */

interface Word {
  id: number;
  english: string;
  chinese: string;
  pronunciation: string;
  category: string;
}

const wordCategories = {
  Fruits: [
    ['Apple', '苹果', 'AP-ul'],
    ['Banana', '香蕉', 'BAN-uh'],
    ['Orange', '橙子', 'OR-inj'],
    ['Strawberry', '草莓', 'STRAW-ber-ee'],
    ['Watermelon', '西瓜', 'WO-ter-mel-un'],
    ['Grape', '葡萄', 'GRAYP'],
    ['Lemon', '柠檬', 'LEM-un'],
    ['Mango', '芒果', 'MANG-go'],
    ['Pear', '梨', 'PAIR'],
    ['Peach', '桃子', 'PEECH'],
    ['Pineapple', '菠萝', 'PY-nap-ul'],
    ['Blueberry', '蓝莓', 'BLOO-ber-ee'],
    ['Raspberry', '树莓', 'RAZ-ber-ee'],
    ['Kiwi', '猕猴桃', 'KEE-wee'],
    ['Coconut', '椰子', 'KO-ko-nut'],
    ['Cherry', '樱桃', 'CHER-ee'],
    ['Papaya', '木瓜', 'puh-PY-uh'],
    ['Plum', '李子', 'PLUM'],
    ['Lime', '青柠', 'LYM'],
    ['Avocado', '牛油果', 'av-uh-KAH-do'],
    ['Tangerine', '橘子', 'tan-jer-EEN'],
    ['Grapefruit', '葡萄柚', 'GRAYP-froot'],
    ['Pomegranate', '石榴', 'PAM-uh-gran-it'],
    ['Fig', '无花果', 'FIG'],
    ['Date', '枣', 'DAYT'],
    ['Apricot', '杏', 'AY-pruh-kot'],
    ['Guava', '番石榴', 'GWAH-vuh'],
    ['Passion fruit', '百香果', 'PASH-un FROOT'],
    ['Lychee', '荔枝', 'LEE-chee'],
    ['Dragonfruit', '火龙果', 'DRAG-un-froot'],
    ['Blackberry', '黑莓', 'BLA-ber-ee'],
    ['Cantaloupe', '哈密瓜', 'CAN-tuh-lope'],
    ['Honeydew', '蜜瓜', 'HUN-ee-doo'],
    ['Nectarine', '油桃', 'NEC-tuh-reen'],
    ['Persimmon', '柿子', 'per-SIM-un'],
    ['Quince', '榅桲', 'KWINS'],
    ['Rambutan', '红毛丹', 'ram-BOO-tun'],
    ['Starfruit', '杨桃', 'STAR-froot'],
    ['Mulberry', '桑葚', 'MUL-ber-ee'],
    ['Elderberry', '接骨木浆果', 'EL-der-ber-ee'],
  ],
  Vegetables: [
    ['Carrot', '胡萝卜', 'KAR-ut'],
    ['Tomato', '番茄', 'tuh-MAH-to'],
    ['Potato', '土豆', 'puh-TAY-to'],
    ['Broccoli', '西兰花', 'BROK-uh-lee'],
    ['Cabbage', '卷心菜', 'KAB-ij'],
    ['Cucumber', '黄瓜', 'KYO-kum-ber'],
    ['Lettuce', '生菜', 'LET-us'],
    ['Onion', '洋葱', 'UN-yun'],
    ['Pepper', '辣椒', 'PEP-er'],
    ['Corn', '玉米', 'KORN'],
    ['Spinach', '菠菜', 'SPIN-ij'],
    ['Pumpkin', '南瓜', 'PUM-kin'],
    ['Eggplant', '茄子', 'EG-plant'],
    ['Garlic', '大蒜', 'GAR-lik'],
    ['Mushroom', '蘑菇', 'MUSH-room'],
    ['Celery', '芹菜', 'SEL-uh-ree'],
    ['Radish', '萝卜', 'RAD-ish'],
    ['Zucchini', '西葫芦', 'zoo-KEE-nee'],
    ['Asparagus', '芦笋', 'uh-SPAR-uh-gus'],
    ['Beet', '甜菜', 'BEET'],
    ['Peas', '豌豆', 'PEEZ'],
    ['Beans', '豆类', 'BEENZ'],
    ['Cauliflower', '花菜', 'KO-luh-flow-er'],
    ['Kale', '羽衣甘蓝', 'KAYL'],
    ['Leek', '韭葱', 'LEEK'],
    ['Chard', '牛皮菜', 'CHARD'],
    ['Arugula', '芝麻菜', 'uh-ROO-guh-luh'],
    ['Parsnip', '欧洲防风草', 'PAR-snip'],
    ['Turnip', '芜菁', 'TER-nip'],
    ['Squash', '南瓜', 'SKWOSH'],
    ['Artichoke', '洋蓟', 'AR-ti-chok'],
    ['Brussels sprouts', '抱子甘蓝', 'BRUS-ulz SPROUTS'],
    ['Bok choy', '小白菜', 'BOK CHOY'],
    ['Broccoli rabe', '芥兰', 'BROK-uh-lee RAHB'],
    ['Cardoon', '刺蓟', 'kar-DOON'],
    ['Celeriac', '芹菜根', 'sel-ER-ee-ak'],
    ['Chicory', '菊苣', 'CHIK-uh-ree'],
    ['Collard greens', '羽衣甘蓝', 'KOL-erd GREENZ'],
    ['Daikon', '白萝卜', 'DY-kon'],
    ['Endive', '菊苣', 'EN-dyv'],
  ],
  Food: [
    ['Bread', '面包', 'BRED'],
    ['Rice', '米饭', 'RYS'],
    ['Milk', '牛奶', 'MILK'],
    ['Cheese', '奶酪', 'CHEEZ'],
    ['Egg', '鸡蛋', 'EG'],
    ['Chicken', '鸡肉', 'CHIK-un'],
    ['Fish', '鱼', 'FISH'],
    ['Meat', '肉', 'MEET'],
    ['Soup', '汤', 'SOOP'],
    ['Noodle', '面条', 'NOO-dul'],
    ['Pizza', '披萨', 'PEET-suh'],
    ['Hamburger', '汉堡', 'HAM-ber-ger'],
    ['Sandwich', '三明治', 'SAN-wich'],
    ['Salad', '沙拉', 'SAL-ud'],
    ['Butter', '黄油', 'BUT-er'],
    ['Honey', '蜂蜜', 'HUN-ee'],
    ['Sugar', '糖', 'SHOO-ger'],
    ['Salt', '盐', 'SAWLT'],
    ['Oil', '油', 'OYL'],
    ['Water', '水', 'WO-ter'],
    ['Juice', '果汁', 'JOOS'],
    ['Tea', '茶', 'TEE'],
    ['Coffee', '咖啡', 'KO-fee'],
    ['Cake', '蛋糕', 'KAYK'],
    ['Cookie', '饼干', 'KOO-kee'],
    ['Pasta', '意大利面', 'PAS-tuh'],
    ['Yogurt', '酸奶', 'YO-gurt'],
    ['Bacon', '培根', 'BAY-kun'],
    ['Sausage', '香肠', 'SO-sij'],
    ['Tofu', '豆腐', 'TO-foo'],
    ['Dumpling', '饺子', 'DUM-pling'],
    ['Sushi', '寿司', 'SOO-shee'],
    ['Taco', '玉米卷', 'TAH-ko'],
    ['Burrito', '卷饼', 'buh-REE-to'],
    ['Steak', '牛排', 'STAYK'],
    ['Pork', '猪肉', 'PORK'],
    ['Beef', '牛肉', 'BEEF'],
    ['Lamb', '羊肉', 'LAM'],
    ['Shrimp', '虾', 'SHRIMP'],
    ['Crab', '螃蟹', 'KRAB'],
  ],
  Animals: [
    ['Cat', '猫', 'KAT'],
    ['Dog', '狗', 'DOG'],
    ['Bird', '鸟', 'BERD'],
    ['Elephant', '大象', 'EL-uh-funt'],
    ['Lion', '狮子', 'LY-un'],
    ['Tiger', '老虎', 'TY-ger'],
    ['Bear', '熊', 'BAIR'],
    ['Monkey', '猴子', 'MUN-kee'],
    ['Rabbit', '兔子', 'RAB-it'],
    ['Deer', '鹿', 'DEER'],
    ['Horse', '马', 'HORS'],
    ['Cow', '牛', 'KOW'],
    ['Pig', '猪', 'PIG'],
    ['Sheep', '羊', 'SHEEP'],
    ['Goat', '山羊', 'GOT'],
    ['Duck', '鸭子', 'DUK'],
    ['Butterfly', '蝴蝶', 'BUT-er-fly'],
    ['Bee', '蜜蜂', 'BEE'],
    ['Snake', '蛇', 'SNAYK'],
    ['Frog', '青蛙', 'FROG'],
    ['Turtle', '乌龟', 'TER-tul'],
    ['Penguin', '企鹅', 'PEN-gwin'],
    ['Panda', '熊猫', 'PAN-duh'],
    ['Giraffe', '长颈鹿', 'juh-RAF'],
    ['Zebra', '斑马', 'ZEE-bruh'],
    ['Kangaroo', '袋鼠', 'kang-guh-ROO'],
    ['Koala', '考拉', 'ko-AH-luh'],
    ['Whale', '鲸鱼', 'WAYL'],
    ['Shark', '鲨鱼', 'SHARK'],
    ['Dolphin', '海豚', 'DOL-fin'],
    ['Owl', '猫头鹰', 'OWL'],
    ['Eagle', '鹰', 'EE-gul'],
    ['Parrot', '鹦鹉', 'PAIR-ut'],
    ['Peacock', '孔雀', 'PEE-kok'],
    ['Ostrich', '鸵鸟', 'AHS-trich'],
    ['Flamingo', '火烈鸟', 'fluh-MING-go'],
    ['Swan', '天鹅', 'SWAN'],
    ['Crocodile', '鳄鱼', 'KROK-uh-dyl'],
    ['Alligator', '短吻鳄', 'AL-uh-gay-ter'],
    ['Lizard', '蜥蜴', 'LIZ-erd'],
  ],
  Colors: [
    ['Red', '红色', 'RED'],
    ['Blue', '蓝色', 'BLOO'],
    ['Green', '绿色', 'GREEN'],
    ['Yellow', '黄色', 'YEL-o'],
    ['Orange', '橙色', 'OR-inj'],
    ['Purple', '紫色', 'PER-pul'],
    ['Pink', '粉红色', 'PINGK'],
    ['Brown', '棕色', 'BROWN'],
    ['Black', '黑色', 'BLAK'],
    ['White', '白色', 'WHYT'],
    ['Gray', '灰色', 'GRAY'],
    ['Cyan', '青色', 'SY-an'],
    ['Magenta', '洋红色', 'muh-JEN-tuh'],
    ['Lime', '酸橙色', 'LYM'],
    ['Navy', '海军蓝', 'NAY-vee'],
    ['Maroon', '栗色', 'muh-ROON'],
    ['Olive', '橄榄色', 'AHL-iv'],
    ['Coral', '珊瑚色', 'KOR-ul'],
    ['Salmon', '鲑鱼色', 'SAM-un'],
    ['Gold', '金色', 'GOLD'],
  ],
  Numbers: [
    ['One', '一', 'WUN'],
    ['Two', '二', 'TOO'],
    ['Three', '三', 'THREE'],
    ['Four', '四', 'FOR'],
    ['Five', '五', 'FYV'],
    ['Six', '六', 'SIKS'],
    ['Seven', '七', 'SEV-un'],
    ['Eight', '八', 'AYT'],
    ['Nine', '九', 'NYN'],
    ['Ten', '十', 'TEN'],
    ['Eleven', '十一', 'ih-LEV-un'],
    ['Twelve', '十二', 'TWELV'],
    ['Thirteen', '十三', 'ther-TEEN'],
    ['Fourteen', '十四', 'for-TEEN'],
    ['Fifteen', '十五', 'fif-TEEN'],
    ['Sixteen', '十六', 'sik-STEEN'],
    ['Seventeen', '十七', 'sev-un-TEEN'],
    ['Eighteen', '十八', 'ay-TEEN'],
    ['Nineteen', '十九', 'ny-TEEN'],
    ['Twenty', '二十', 'TWEN-tee'],
  ],
  Body: [
    ['Head', '头', 'HED'],
    ['Eye', '眼睛', 'AY'],
    ['Nose', '鼻子', 'NOZ'],
    ['Mouth', '嘴', 'MOUTH'],
    ['Ear', '耳朵', 'EER'],
    ['Tooth', '牙齿', 'TOOTH'],
    ['Tongue', '舌头', 'TUNG'],
    ['Hand', '手', 'HAND'],
    ['Finger', '手指', 'FING-ger'],
    ['Arm', '胳膊', 'ARM'],
    ['Leg', '腿', 'LEG'],
    ['Foot', '脚', 'FOOT'],
    ['Toe', '脚趾', 'TO'],
    ['Heart', '心脏', 'HART'],
    ['Lung', '肺', 'LUNG'],
    ['Stomach', '胃', 'STUM-ik'],
    ['Brain', '大脑', 'BRAYN'],
    ['Bone', '骨头', 'BON'],
    ['Skin', '皮肤', 'SKIN'],
    ['Hair', '头发', 'HAIR'],
  ],
  School: [
    ['School', '学校', 'SKOOL'],
    ['Teacher', '老师', 'TEECH-er'],
    ['Student', '学生', 'STOO-dent'],
    ['Classroom', '教室', 'KLAS-room'],
    ['Desk', '书桌', 'DESK'],
    ['Chair', '椅子', 'CHAIR'],
    ['Blackboard', '黑板', 'BLAK-bord'],
    ['Chalk', '粉笔', 'CHOK'],
    ['Eraser', '橡皮', 'ih-RAY-zer'],
    ['Book', '书', 'BOOK'],
    ['Pen', '笔', 'PEN'],
    ['Pencil', '铅笔', 'PEN-sul'],
    ['Paper', '纸', 'PAY-per'],
    ['Notebook', '笔记本', 'NOT-book'],
    ['Backpack', '背包', 'BAK-pak'],
    ['Locker', '储物柜', 'LOK-er'],
    ['Library', '图书馆', 'LY-brer-ee'],
    ['Playground', '操场', 'PLAY-ground'],
    ['Cafeteria', '食堂', 'kaf-uh-TEER-ee-uh'],
    ['Gym', '体育馆', 'JIM'],
  ],
};

export function generateWords(): Word[] {
  const words: Word[] = [];
  let id = 1;

  for (const [category, wordList] of Object.entries(wordCategories)) {
    for (const [english, chinese, pronunciation] of wordList) {
      words.push({
        id,
        english,
        chinese,
        pronunciation,
        category,
      });
      id++;
    }
  }

  return words;
}
