/**
 * 单词生成工具
 * 使用简洁的数据结构生成500个单词
 */

interface Word {
  id: number;
  english: string;
  chinese: string;
  pronunciation: string;
  category: string;
}

const wordCategories = {
  Fruits: [
    ['Apple', '苹果', 'AP-ul'],
    ['Banana', '香蕉', 'BAN-uh'],
    ['Orange', '橙子', 'OR-inj'],
    ['Strawberry', '草莓', 'STRAW-ber-ee'],
    ['Watermelon', '西瓜', 'WO-ter-mel-un'],
    ['Grape', '葡萄', 'GRAYP'],
    ['Lemon', '柠檬', 'LEM-un'],
    ['Mango', '芒果', 'MANG-go'],
    ['Pear', '梨', 'PAIR'],
    ['Peach', '桃子', 'PEECH'],
    ['Pineapple', '菠萝', 'PY-nap-ul'],
    ['Blueberry', '蓝莓', 'BLOO-ber-ee'],
    ['Raspberry', '树莓', 'RAZ-ber-ee'],
    ['Kiwi', '猕猴桃', 'KEE-wee'],
    ['Coconut', '椰子', 'KO-ko-nut'],
    ['Cherry', '樱桃', 'CHER-ee'],
    ['Papaya', '木瓜', 'puh-PY-uh'],
    ['Plum', '李子', 'PLUM'],
    ['Lime', '青柠', 'LYM'],
    ['Avocado', '牛油果', 'av-uh-KAH-do'],
    ['Tangerine', '橘子', 'tan-jer-EEN'],
    ['Grapefruit', '葡萄柚', 'GRAYP-froot'],
    ['Pomegranate', '石榴', 'PAM-uh-gran-it'],
    ['Fig', '无花果', 'FIG'],
    ['Date', '枣', 'DAYT'],
    ['Apricot', '杏', 'AY-pruh-kot'],
    ['Guava', '番石榴', 'GWAH-vuh'],
    ['Passion fruit', '百香果', 'PASH-un FROOT'],
    ['Lychee', '荔枝', 'LEE-chee'],
    ['Dragonfruit', '火龙果', 'DRAG-un-froot'],
    ['Blackberry', '黑莓', 'BLA-ber-ee'],
    ['Cantaloupe', '哈密瓜', 'CAN-tuh-lope'],
    ['Honeydew', '蜜瓜', 'HUN-ee-doo'],
    ['Nectarine', '油桃', 'NEC-tuh-reen'],
    ['Persimmon', '柿子', 'per-SIM-un'],
    ['Quince', '榅桲', 'KWINS'],
    ['Rambutan', '红毛丹', 'ram-BOO-tun'],
    ['Starfruit', '杨桃', 'STAR-froot'],
    ['Mulberry', '桑葚', 'MUL-ber-ee'],
    ['Elderberry', '接骨木浆果', 'EL-der-ber-ee'],
    ['Acai', '巴西莓', 'ah-sah-EE'],
    ['Bilberry', '越橘', 'BIL-ber-ee'],
    ['Boysenberry', '黑莓', 'BOY-sen-ber-ee'],
    ['Cranberry', '蔓越莓', 'KRAN-ber-ee'],
    ['Currant', '黑加仑', 'KUR-unt'],
    ['Gooseberry', '醋栗', 'GOOS-ber-ee'],
    ['Huckleberry', '越橘', 'HUK-ul-ber-ee'],
    ['Loganberry', '露莓', 'LO-gun-ber-ee'],
    ['Marionberry', '玛瑞恩莓', 'MAIR-ee-un-ber-ee'],
    ['Medlar', '欧查果', 'MED-lar'],
    ['Mulberry', '桑葚', 'MUL-ber-ee'],
    ['Nectarine', '油桃', 'NEC-tuh-reen'],
    ['Olive', '橄榄', 'AHL-iv'],
    ['Pawpaw', '番木瓜', 'PAW-paw'],
  ],
  Vegetables: [
    ['Carrot', '胡萝卜', 'KAR-ut'],
    ['Tomato', '番茄', 'tuh-MAH-to'],
    ['Potato', '土豆', 'puh-TAY-to'],
    ['Broccoli', '西兰花', 'BROK-uh-lee'],
    ['Cabbage', '卷心菜', 'KAB-ij'],
    ['Cucumber', '黄瓜', 'KYO-kum-ber'],
    ['Lettuce', '生菜', 'LET-us'],
    ['Onion', '洋葱', 'UN-yun'],
    ['Pepper', '辣椒', 'PEP-er'],
    ['Corn', '玉米', 'KORN'],
    ['Spinach', '菠菜', 'SPIN-ij'],
    ['Pumpkin', '南瓜', 'PUM-kin'],
    ['Eggplant', '茄子', 'EG-plant'],
    ['Garlic', '大蒜', 'GAR-lik'],
    ['Mushroom', '蘑菇', 'MUSH-room'],
    ['Celery', '芹菜', 'SEL-uh-ree'],
    ['Radish', '萝卜', 'RAD-ish'],
    ['Zucchini', '西葫芦', 'zoo-KEE-nee'],
    ['Asparagus', '芦笋', 'uh-SPAR-uh-gus'],
    ['Beet', '甜菜', 'BEET'],
    ['Peas', '豌豆', 'PEEZ'],
    ['Beans', '豆类', 'BEENZ'],
    ['Cauliflower', '花菜', 'KO-luh-flow-er'],
    ['Kale', '羽衣甘蓝', 'KAYL'],
    ['Leek', '韭葱', 'LEEK'],
    ['Chard', '牛皮菜', 'CHARD'],
    ['Arugula', '芝麻菜', 'uh-ROO-guh-luh'],
    ['Parsnip', '欧洲防风草', 'PAR-snip'],
    ['Turnip', '芜菁', 'TER-nip'],
    ['Squash', '南瓜', 'SKWOSH'],
    ['Artichoke', '洋蓟', 'AR-ti-chok'],
    ['Brussels sprouts', '抱子甘蓝', 'BRUS-ulz SPROUTS'],
    ['Bok choy', '小白菜', 'BOK CHOY'],
    ['Broccoli rabe', '芥兰', 'BROK-uh-lee RAHB'],
    ['Cardoon', '刺蓟', 'kar-DOON'],
    ['Celeriac', '芹菜根', 'sel-ER-ee-ak'],
    ['Chicory', '菊苣', 'CHIK-uh-ree'],
    ['Collard greens', '羽衣甘蓝', 'KOL-erd GREENZ'],
    ['Daikon', '白萝卜', 'DY-kon'],
    ['Endive', '菊苣', 'EN-dyv'],
    ['Fennel', '茴香', 'FEN-ul'],
    ['Jicama', '豆薯', 'HEE-kuh-muh'],
    ['Kohlrabi', '球茎甘蓝', 'KOL-rah-bee'],
    ['Okra', '秋葵', 'O-kruh'],
    ['Scallion', '葱', 'SKAL-yun'],
    ['Shallot', '小洋葱', 'shuh-LOT'],
    ['Watercress', '豆瓣菜', 'WO-ter-kres'],
  ],
  Food: [
    ['Bread', '面包', 'BRED'],
    ['Rice', '米饭', 'RYS'],
    ['Milk', '牛奶', 'MILK'],
    ['Cheese', '奶酪', 'CHEEZ'],
    ['Egg', '鸡蛋', 'EG'],
    ['Chicken', '鸡肉', 'CHIK-un'],
    ['Fish', '鱼', 'FISH'],
    ['Meat', '肉', 'MEET'],
    ['Soup', '汤', 'SOOP'],
    ['Noodle', '面条', 'NOO-dul'],
    ['Pizza', '披萨', 'PEET-suh'],
    ['Hamburger', '汉堡', 'HAM-ber-ger'],
    ['Sandwich', '三明治', 'SAN-wich'],
    ['Salad', '沙拉', 'SAL-ud'],
    ['Butter', '黄油', 'BUT-er'],
    ['Honey', '蜂蜜', 'HUN-ee'],
    ['Sugar', '糖', 'SHOO-ger'],
    ['Salt', '盐', 'SAWLT'],
    ['Oil', '油', 'OYL'],
    ['Water', '水', 'WO-ter'],
    ['Juice', '果汁', 'JOOS'],
    ['Tea', '茶', 'TEE'],
    ['Coffee', '咖啡', 'KO-fee'],
    ['Cake', '蛋糕', 'KAYK'],
    ['Cookie', '饼干', 'KOO-kee'],
    ['Pasta', '意大利面', 'PAS-tuh'],
    ['Yogurt', '酸奶', 'YO-gurt'],
    ['Bacon', '培根', 'BAY-kun'],
    ['Sausage', '香肠', 'SO-sij'],
    ['Tofu', '豆腐', 'TO-foo'],
    ['Dumpling', '饺子', 'DUM-pling'],
    ['Sushi', '寿司', 'SOO-shee'],
    ['Taco', '玉米卷', 'TAH-ko'],
    ['Burrito', '卷饼', 'buh-REE-to'],
    ['Steak', '牛排', 'STAYK'],
    ['Pork', '猪肉', 'PORK'],
    ['Beef', '牛肉', 'BEEF'],
    ['Lamb', '羊肉', 'LAM'],
    ['Shrimp', '虾', 'SHRIMP'],
    ['Crab', '螃蟹', 'KRAB'],
    ['Lobster', '龙虾', 'LOB-ster'],
    ['Oyster', '牡蛎', 'OY-ster'],
    ['Clam', '蛤蜊', 'KLAM'],
    ['Scallop', '扇贝', 'SKAL-up'],
    ['Mussels', '贻贝', 'MUS-ulz'],
    ['Squid', '鱿鱼', 'SKWID'],
    ['Octopus', '章鱼', 'OK-tuh-pus'],
    ['Caviar', '鱼子酱', 'KAV-ee-ar'],
    ['Foie gras', '鹅肝', 'FWAH GRAH'],
  ],
  Animals: [
    ['Cat', '猫', 'KAT'],
    ['Dog', '狗', 'DOG'],
    ['Bird', '鸟', 'BERD'],
    ['Elephant', '大象', 'EL-uh-funt'],
    ['Lion', '狮子', 'LY-un'],
    ['Tiger', '老虎', 'TY-ger'],
    ['Bear', '熊', 'BAIR'],
    ['Monkey', '猴子', 'MUN-kee'],
    ['Rabbit', '兔子', 'RAB-it'],
    ['Deer', '鹿', 'DEER'],
    ['Horse', '马', 'HORS'],
    ['Cow', '牛', 'KOW'],
    ['Pig', '猪', 'PIG'],
    ['Sheep', '羊', 'SHEEP'],
    ['Goat', '山羊', 'GOT'],
    ['Duck', '鸭子', 'DUK'],
    ['Butterfly', '蝴蝶', 'BUT-er-fly'],
    ['Bee', '蜜蜂', 'BEE'],
    ['Snake', '蛇', 'SNAYK'],
    ['Frog', '青蛙', 'FROG'],
    ['Turtle', '乌龟', 'TER-tul'],
    ['Penguin', '企鹅', 'PEN-gwin'],
    ['Panda', '熊猫', 'PAN-duh'],
    ['Giraffe', '长颈鹿', 'juh-RAF'],
    ['Zebra', '斑马', 'ZEE-bruh'],
    ['Kangaroo', '袋鼠', 'kang-guh-ROO'],
    ['Koala', '考拉', 'ko-AH-luh'],
    ['Whale', '鲸鱼', 'WAYL'],
    ['Shark', '鲨鱼', 'SHARK'],
    ['Dolphin', '海豚', 'DOL-fin'],
    ['Owl', '猫头鹰', 'OWL'],
    ['Eagle', '鹰', 'EE-gul'],
    ['Parrot', '鹦鹉', 'PAIR-ut'],
    ['Peacock', '孔雀', 'PEE-kok'],
    ['Ostrich', '鸵鸟', 'AHS-trich'],
    ['Flamingo', '火烈鸟', 'fluh-MING-go'],
    ['Swan', '天鹅', 'SWAN'],
    ['Crocodile', '鳄鱼', 'KROK-uh-dyl'],
    ['Alligator', '短吻鳄', 'AL-uh-gay-ter'],
    ['Lizard', '蜥蜴', 'LIZ-erd'],
    ['Iguana', '绿鬣蜥', 'ih-GWAH-nuh'],
    ['Python', '蟒蛇', 'PY-thun'],
    ['Cobra', '眼镜蛇', 'KO-bruh'],
    ['Ant', '蚂蚁', 'ANT'],
    ['Spider', '蜘蛛', 'SPY-der'],
    ['Scorpion', '蝎子', 'SKOR-pee-un'],
    ['Beetle', '甲虫', 'BEE-tul'],
  ],
  Colors: [
    ['Red', '红色', 'RED'],
    ['Blue', '蓝色', 'BLOO'],
    ['Green', '绿色', 'GREEN'],
    ['Yellow', '黄色', 'YEL-o'],
    ['Orange', '橙色', 'OR-inj'],
    ['Purple', '紫色', 'PER-pul'],
    ['Pink', '粉红色', 'PINGK'],
    ['Brown', '棕色', 'BROWN'],
    ['Black', '黑色', 'BLAK'],
    ['White', '白色', 'WHYT'],
    ['Gray', '灰色', 'GRAY'],
    ['Cyan', '青色', 'SY-an'],
    ['Magenta', '洋红色', 'muh-JEN-tuh'],
    ['Lime', '酸橙色', 'LYM'],
    ['Navy', '海军蓝', 'NAY-vee'],
    ['Maroon', '栗色', 'muh-ROON'],
    ['Olive', '橄榄色', 'AHL-iv'],
    ['Coral', '珊瑚色', 'KOR-ul'],
    ['Salmon', '鲑鱼色', 'SAM-un'],
    ['Gold', '金色', 'GOLD'],
    ['Silver', '银色', 'SIL-ver'],
    ['Turquoise', '绿松石色', 'TER-kwoiz'],
    ['Indigo', '靛蓝', 'IN-dih-go'],
    ['Violet', '紫罗兰色', 'VY-uh-lit'],
    ['Scarlet', '深红色', 'SKAR-lit'],
    ['Crimson', '深红色', 'KRIM-zun'],
    ['Beige', '米色', 'BAYZH'],
    ['Tan', '褐色', 'TAN'],
    ['Khaki', '卡其色', 'KAH-kee'],
    ['Ivory', '象牙色', 'AY-vuh-ree'],
  ],
  Numbers: [
    ['One', '一', 'WUN'],
    ['Two', '二', 'TOO'],
    ['Three', '三', 'THREE'],
    ['Four', '四', 'FOR'],
    ['Five', '五', 'FYV'],
    ['Six', '六', 'SIKS'],
    ['Seven', '七', 'SEV-un'],
    ['Eight', '八', 'AYT'],
    ['Nine', '九', 'NYN'],
    ['Ten', '十', 'TEN'],
    ['Eleven', '十一', 'ih-LEV-un'],
    ['Twelve', '十二', 'TWELV'],
    ['Thirteen', '十三', 'ther-TEEN'],
    ['Fourteen', '十四', 'for-TEEN'],
    ['Fifteen', '十五', 'fif-TEEN'],
    ['Sixteen', '十六', 'sik-STEEN'],
    ['Seventeen', '十七', 'sev-un-TEEN'],
    ['Eighteen', '十八', 'ay-TEEN'],
    ['Nineteen', '十九', 'ny-TEEN'],
    ['Twenty', '二十', 'TWEN-tee'],
    ['Thirty', '三十', 'THER-tee'],
    ['Forty', '四十', 'FOR-tee'],
    ['Fifty', '五十', 'FIF-tee'],
    ['Sixty', '六十', 'SIK-stee'],
    ['Seventy', '七十', 'SEV-un-tee'],
    ['Eighty', '八十', 'AY-tee'],
    ['Ninety', '九十', 'NY-nuh-tee'],
    ['Hundred', '一百', 'HUN-dred'],
    ['Thousand', '一千', 'THOU-zund'],
    ['Million', '一百万', 'MIL-yun'],
  ],
  Body: [
    ['Head', '头', 'HED'],
    ['Eye', '眼睛', 'AY'],
    ['Nose', '鼻子', 'NOZ'],
    ['Mouth', '嘴', 'MOUTH'],
    ['Ear', '耳朵', 'EER'],
    ['Tooth', '牙齿', 'TOOTH'],
    ['Tongue', '舌头', 'TUNG'],
    ['Hand', '手', 'HAND'],
    ['Finger', '手指', 'FING-ger'],
    ['Arm', '胳膊', 'ARM'],
    ['Leg', '腿', 'LEG'],
    ['Foot', '脚', 'FOOT'],
    ['Toe', '脚趾', 'TO'],
    ['Heart', '心脏', 'HART'],
    ['Lung', '肺', 'LUNG'],
    ['Stomach', '胃', 'STUM-ik'],
    ['Brain', '大脑', 'BRAYN'],
    ['Bone', '骨头', 'BON'],
    ['Skin', '皮肤', 'SKIN'],
    ['Hair', '头发', 'HAIR'],
    ['Neck', '脖子', 'NEK'],
    ['Shoulder', '肩膀', 'SHOL-der'],
    ['Elbow', '肘部', 'EL-bo'],
    ['Wrist', '手腕', 'RIST'],
    ['Hip', '臀部', 'HIP'],
    ['Knee', '膝盖', 'NEE'],
    ['Ankle', '脚踝', 'ANG-kul'],
    ['Heel', '脚跟', 'HEEL'],
    ['Chin', '下巴', 'CHIN'],
    ['Forehead', '额头', 'FOR-hed'],
  ],
  School: [
    ['School', '学校', 'SKOOL'],
    ['Teacher', '老师', 'TEECH-er'],
    ['Student', '学生', 'STOO-dent'],
    ['Classroom', '教室', 'KLAS-room'],
    ['Desk', '书桌', 'DESK'],
    ['Chair', '椅子', 'CHAIR'],
    ['Blackboard', '黑板', 'BLAK-bord'],
    ['Chalk', '粉笔', 'CHOK'],
    ['Eraser', '橡皮', 'ih-RAY-zer'],
    ['Book', '书', 'BOOK'],
    ['Pen', '笔', 'PEN'],
    ['Pencil', '铅笔', 'PEN-sul'],
    ['Paper', '纸', 'PAY-per'],
    ['Notebook', '笔记本', 'NOT-book'],
    ['Backpack', '背包', 'BAK-pak'],
    ['Locker', '储物柜', 'LOK-er'],
    ['Library', '图书馆', 'LY-brer-ee'],
    ['Playground', '操场', 'PLAY-ground'],
    ['Cafeteria', '食堂', 'kaf-uh-TEER-ee-uh'],
    ['Gym', '体育馆', 'JIM'],
    ['Laboratory', '实验室', 'LAB-uh-tor-ee'],
    ['Computer', '电脑', 'kum-PYOO-ter'],
    ['Keyboard', '键盘', 'KEY-bord'],
    ['Mouse', '鼠标', 'MOUS'],
    ['Monitor', '显示器', 'MON-uh-ter'],
    ['Printer', '打印机', 'PRIN-ter'],
    ['Textbook', '教科书', 'TEKS-book'],
    ['Dictionary', '字典', 'DIK-shuh-ner-ee'],
    ['Homework', '家庭作业', 'HOM-wurk'],
    ['Exam', '考试', 'ig-ZAM'],
  ],
  Nature: [
    ['Mountain', '山', 'MOUN-tin'],
    ['River', '河', 'RIV-er'],
    ['Lake', '湖', 'LAYK'],
    ['Beach', '海滩', 'BEECH'],
    ['Forest', '森林', 'FOR-ist'],
    ['Desert', '沙漠', 'DEZ-ert'],
    ['Jungle', '丛林', 'JUNG-gul'],
    ['Meadow', '草地', 'MED-o'],
    ['Valley', '山谷', 'VAL-ee'],
    ['Swamp', '沼泽', 'SWAMP'],
    ['Marsh', '沼地', 'MARSH'],
    ['Canyon', '峡谷', 'KAN-yun'],
    ['Cliff', '悬崖', 'KLIF'],
    ['Waterfall', '瀑布', 'WO-ter-fol'],
    ['Spring', '泉水', 'SPRING'],
    ['Stream', '溪流', 'STREAM'],
    ['Pond', '池塘', 'POND'],
    ['Glacier', '冰川', 'GLAY-sher'],
    ['Island', '岛屿', 'EYE-lund'],
    ['Peninsula', '半岛', 'puh-NIN-suh-luh'],
    ['Bay', '海湾', 'BAY'],
    ['Gulf', '海湾', 'GULF'],
    ['Strait', '海峡', 'STRAYT'],
    ['Reef', '礁石', 'REEF'],
    ['Volcano', '火山', 'vol-KAY-no'],
    ['Earthquake', '地震', 'ERTH-kwayk'],
    ['Storm', '风暴', 'STORM'],
    ['Thunder', '雷声', 'THUN-der'],
    ['Lightning', '闪电', 'LYT-ning'],
    ['Rainbow', '彩虹', 'RAYN-bo'],
  ],
  Weather: [
    ['Sunny', '晴天', 'SUN-ee'],
    ['Rainy', '下雨', 'RAYN-ee'],
    ['Cloudy', '多云', 'KLOWD-ee'],
    ['Snowy', '下雪', 'SNO-ee'],
    ['Windy', '有风', 'WIN-dee'],
    ['Foggy', '有雾', 'FOG-ee'],
    ['Hot', '热', 'HOT'],
    ['Cold', '冷', 'KOLD'],
    ['Warm', '温暖', 'WORM'],
    ['Cool', '凉爽', 'KOOL'],
    ['Frost', '霜冻', 'FROST'],
    ['Dew', '露水', 'DOO'],
    ['Hail', '冰雹', 'HAYL'],
    ['Sleet', '冻雨', 'SLEET'],
    ['Tornado', '龙卷风', 'tor-NAY-do'],
    ['Hurricane', '飓风', 'HER-uh-kayn'],
    ['Blizzard', '暴雪', 'BLIZ-erd'],
    ['Drought', '干旱', 'DROUT'],
    ['Flood', '洪水', 'FLUD'],
    ['Temperature', '温度', 'TEM-per-uh-chur'],
    ['Humidity', '湿度', 'hyoo-MID-uh-tee'],
    ['Pressure', '气压', 'PRESH-er'],
    ['Wind', '风', 'WIND'],
    ['Breeze', '微风', 'BREEZ'],
    ['Gust', '阵风', 'GUST'],
    ['Calm', '平静', 'KAHM'],
    ['Mild', '温和', 'MYLD'],
    ['Severe', '严重', 'suh-VEER'],
    ['Extreme', '极端', 'ik-STREEM'],
    ['Variable', '多变', 'VAIR-ee-uh-bul'],
  ],
  Sports: [
    ['Football', '足球', 'FOOT-bawl'],
    ['Basketball', '篮球', 'BAS-kit-bawl'],
    ['Tennis', '网球', 'TEN-is'],
    ['Baseball', '棒球', 'BASE-bawl'],
    ['Volleyball', '排球', 'VOL-ee-bawl'],
    ['Badminton', '羽毛球', 'BAD-min-tun'],
    ['Swimming', '游泳', 'SWIM-ing'],
    ['Running', '跑步', 'RUN-ing'],
    ['Cycling', '骑自行车', 'SY-kling'],
    ['Skiing', '滑雪', 'SKEE-ing'],
    ['Skating', '溜冰', 'SKAYT-ing'],
    ['Gymnastics', '体操', 'jim-NAS-tiks'],
    ['Boxing', '拳击', 'BOK-sing'],
    ['Wrestling', '摔跤', 'RES-ling'],
    ['Martial arts', '武术', 'MAR-shul ARTS'],
    ['Yoga', '瑜伽', 'YO-guh'],
    ['Pilates', '普拉提', 'pih-LAH-teez'],
    ['Dancing', '舞蹈', 'DAN-sing'],
    ['Surfing', '冲浪', 'SER-fing'],
    ['Skateboarding', '滑板', 'SKAYT-bor-ding'],
    ['Climbing', '爬山', 'KLY-ming'],
    ['Hiking', '远足', 'HY-king'],
    ['Camping', '露营', 'KAM-ping'],
    ['Fishing', '钓鱼', 'FISH-ing'],
    ['Hunting', '狩猎', 'HUN-ting'],
    ['Horseback riding', '骑马', 'HORS-bak RY-ding'],
    ['Kayaking', '皮划艇', 'KY-ak-ing'],
    ['Canoeing', '划独木舟', 'kuh-NOO-ing'],
    ['Sailing', '帆船', 'SAY-ling'],
    ['Archery', '射箭', 'AR-cher-ee'],
  ],
  Transportation: [
    ['Car', '汽车', 'KAR'],
    ['Truck', '卡车', 'TRUK'],
    ['Bus', '公共汽车', 'BUS'],
    ['Train', '火车', 'TRAYN'],
    ['Airplane', '飞机', 'AIR-playn'],
    ['Helicopter', '直升飞机', 'HEL-uh-kop-ter'],
    ['Boat', '小船', 'BOT'],
    ['Ship', '船', 'SHIP'],
    ['Bicycle', '自行车', 'BY-sik-ul'],
    ['Motorcycle', '摩托车', 'MO-ter-sy-kul'],
    ['Taxi', '出租车', 'TAK-see'],
    ['Ambulance', '救护车', 'AM-byuh-lans'],
    ['Police car', '警车', 'puh-LEES KAR'],
    ['Fire truck', '消防车', 'FY-er TRUK'],
    ['Tractor', '拖拉机', 'TRAK-ter'],
    ['Scooter', '滑板车', 'SKOO-ter'],
    ['Roller skates', '滑冰鞋', 'RO-ler SKYTS'],
    ['Wagon', '三轮车', 'WAG-un'],
    ['Subway', '地铁', 'SUB-way'],
    ['Trolley', '电车', 'TROL-ee'],
    ['Cable car', '缆车', 'KAY-bul KAR'],
    ['Gondola', '贡多拉', 'GON-duh-luh'],
    ['Ferry', '渡轮', 'FER-ee'],
    ['Yacht', '游艇', 'YOT'],
    ['Canoe', '独木舟', 'kuh-NOO'],
    ['Raft', '木筏', 'RAFT'],
    ['Glider', '滑翔机', 'GLY-der'],
    ['Parachute', '降落伞', 'PAIR-uh-shoot'],
    ['Rocket', '火箭', 'ROK-it'],
    ['Spaceship', '宇宙飞船', 'SPAYS-ship'],
  ],
  Technology: [
    ['Computer', '电脑', 'kum-PYOO-ter'],
    ['Laptop', '笔记本电脑', 'LAP-top'],
    ['Tablet', '平板电脑', 'TAB-lit'],
    ['Phone', '电话', 'FON'],
    ['Smartphone', '智能手机', 'SMART-fon'],
    ['Camera', '相机', 'KAM-er-uh'],
    ['Television', '电视', 'TEL-uh-vizh-un'],
    ['Radio', '收音机', 'RAY-dee-o'],
    ['Microphone', '麦克风', 'MY-kro-fon'],
    ['Speaker', '扬声器', 'SPEAK-er'],
    ['Headphone', '耳机', 'HED-fon'],
    ['Keyboard', '键盘', 'KEY-bord'],
    ['Mouse', '鼠标', 'MOUS'],
    ['Monitor', '显示器', 'MON-uh-ter'],
    ['Printer', '打印机', 'PRIN-ter'],
    ['Scanner', '扫描仪', 'SKAN-er'],
    ['Router', '路由器', 'ROO-ter'],
    ['Modem', '调制解调器', 'MO-dem'],
    ['Server', '服务器', 'SER-ver'],
    ['Cable', '电缆', 'KAY-bul'],
    ['Battery', '电池', 'BAT-uh-ree'],
    ['Charger', '充电器', 'CHAR-jer'],
    ['USB', 'USB', 'YOU-ES-BEE'],
    ['Wifi', '无线网络', 'WY-fy'],
    ['Bluetooth', '蓝牙', 'BLOO-tooth'],
    ['Cloud', '云', 'KLOUD'],
    ['Internet', '互联网', 'IN-ter-net'],
    ['Email', '电子邮件', 'EE-mayl'],
    ['Website', '网站', 'WEB-syt'],
    ['App', '应用程序', 'APP'],
  ],
  Clothes: [
    ['Shirt', '衬衫', 'SHERT'],
    ['Pants', '裤子', 'PANTS'],
    ['Dress', '连衣裙', 'DRES'],
    ['Skirt', '裙子', 'SKERT'],
    ['Jacket', '夹克', 'JAK-it'],
    ['Coat', '外套', 'KOT'],
    ['Sweater', '毛衣', 'SWET-er'],
    ['T-shirt', 'T恤', 'TEE-SHERT'],
    ['Shorts', '短裤', 'SHORTS'],
    ['Jeans', '牛仔裤', 'JEENZ'],
    ['Socks', '袜子', 'SOKS'],
    ['Shoes', '鞋', 'SHOOZ'],
    ['Boots', '靴子', 'BOOTS'],
    ['Sandals', '凉鞋', 'SAN-dulz'],
    ['Hat', '帽子', 'HAT'],
    ['Cap', '棒球帽', 'KAP'],
    ['Scarf', '围巾', 'SKARF'],
    ['Gloves', '手套', 'GLUVZ'],
    ['Belt', '腰带', 'BELT'],
    ['Tie', '领带', 'TY'],
    ['Vest', '背心', 'VEST'],
    ['Cardigan', '开衫', 'KAR-dih-gun'],
    ['Hoodie', '连帽衫', 'HOO-dee'],
    ['Raincoat', '雨衣', 'RAYN-kot'],
    ['Blazer', '西装', 'BLAY-zer'],
    ['Tuxedo', '燕尾服', 'tuk-SEE-do'],
    ['Leggings', '紧身裤', 'LEG-ingz'],
    ['Swimsuit', '游泳衣', 'SWIM-soot'],
    ['Pajamas', '睡衣', 'puh-JAH-muz'],
    ['Underwear', '内衣', 'UN-der-wair'],
  ],
  House: [
    ['House', '房子', 'HOUS'],
    ['Kitchen', '厨房', 'KICH-un'],
    ['Bedroom', '卧室', 'BED-room'],
    ['Bathroom', '浴室', 'BATH-room'],
    ['Living room', '客厅', 'LIV-ing ROOM'],
    ['Dining room', '餐厅', 'DY-ning ROOM'],
    ['Hallway', '走廊', 'HAHL-way'],
    ['Stairs', '楼梯', 'STAIRZ'],
    ['Wall', '墙壁', 'WAWL'],
    ['Roof', '屋顶', 'ROOF'],
    ['Floor', '地板', 'FLOR'],
    ['Ceiling', '天花板', 'SEE-ling'],
    ['Door', '门', 'DOR'],
    ['Window', '窗户', 'WIN-do'],
    ['Bed', '床', 'BED'],
    ['Sofa', '沙发', 'SO-fuh'],
    ['Table', '桌子', 'TAY-bul'],
    ['Chair', '椅子', 'CHAIR'],
    ['Lamp', '台灯', 'LAMP'],
    ['Refrigerator', '冰箱', 'rih-FRIJ-uh-ray-ter'],
    ['Stove', '炉子', 'STOV'],
    ['Sink', '水槽', 'SINGK'],
    ['Toilet', '马桶', 'TOY-lit'],
    ['Shower', '淋浴', 'SHOW-er'],
    ['Bathtub', '浴缸', 'BATH-tub'],
    ['Mirror', '镜子', 'MIR-er'],
    ['Cabinet', '橱柜', 'KAB-uh-nit'],
    ['Drawer', '抽屉', 'DROR'],
    ['Closet', '衣柜', 'KLOZ-it'],
    ['Bookshelf', '书架', 'BOOK-shelf'],
  ],
};

export function generateWords(): Word[] {
  const words: Word[] = [];
  let id = 1;

  for (const [category, wordList] of Object.entries(wordCategories)) {
    for (const [english, chinese, pronunciation] of wordList) {
      words.push({
        id,
        english,
        chinese,
        pronunciation,
        category,
      });
      id++;
    }
  }

  return words;
}
