/**
 * 单词生成工具
 * 使用简洁的数据结构生成500个单词
 */

interface Word {
  id: number;
  english: string;
  chinese: string;
  pronunciation: string;
  category: string;
  emoji: string;
}

const wordCategories = {
  Fruits: [
    ['Apple', '苹果', 'AP-ul', '🍎'],
    ['Banana', '香蕉', 'BAN-uh', '🍌'],
    ['Orange', '橙子', 'OR-inj', '🍊'],
    ['Strawberry', '草莓', 'STRAW-ber-ee', '🍓'],
    ['Watermelon', '西瓜', 'WO-ter-mel-un', '🍉'],
    ['Grape', '葡萄', 'GRAYP', '🍇'],
    ['Lemon', '柠檬', 'LEM-un', '🍋'],
    ['Mango', '芒果', 'MANG-go', '🥭'],
    ['Pear', '梨', 'PAIR', '🍐'],
    ['Peach', '桃子', 'PEECH', '🍑'],
    ['Pineapple', '菠萝', 'PY-nap-ul', '🍍'],
    ['Blueberry', '蓝莓', 'BLOO-ber-ee', '🫐'],
    ['Raspberry', '树莓', 'RAZ-ber-ee', '🫐'],
    ['Kiwi', '猕猴桃', 'KEE-wee', '🥝'],
    ['Coconut', '椰子', 'KO-ko-nut', '🥥'],
    ['Cherry', '樱桃', 'CHER-ee', '🍒'],
    ['Papaya', '木瓜', 'puh-PY-uh', '🧡'],
    ['Plum', '李子', 'PLUM', '🍑'],
    ['Lime', '青柠', 'LYM', '🍋'],
    ['Avocado', '牛油果', 'av-uh-KAH-do', '🥑'],
    ['Tangerine', '橘子', 'tan-jer-EEN', '🍊'],
    ['Grapefruit', '葡萄柚', 'GRAYP-froot', '🍊'],
    ['Pomegranate', '石榴', 'PAM-uh-gran-it', '🍒'],
    ['Fig', '无花果', 'FIG', '🟤'],
    ['Date', '枣', 'DAYT', '🟤'],
    ['Apricot', '杏', 'AY-pruh-kot', '🍑'],
    ['Guava', '番石榴', 'GWAH-vuh', '🟢'],
    ['Passion fruit', '百香果', 'PASH-un FROOT', '🟣'],
    ['Lychee', '荔枝', 'LEE-chee', '🔴'],
    ['Dragonfruit', '火龙果', 'DRAG-un-froot', '🩷'],
  ],
  Vegetables: [
    ['Carrot', '胡萝卜', 'KAR-ut', '🥕'],
    ['Tomato', '番茄', 'tuh-MAH-to', '🍅'],
    ['Potato', '土豆', 'puh-TAY-to', '🥔'],
    ['Broccoli', '西兰花', 'BROK-uh-lee', '🥦'],
    ['Cabbage', '卷心菜', 'KAB-ij', '🥬'],
    ['Cucumber', '黄瓜', 'KYO-kum-ber', '🥒'],
    ['Lettuce', '生菜', 'LET-us', '🥬'],
    ['Onion', '洋葱', 'UN-yun', '🧅'],
    ['Pepper', '辣椒', 'PEP-er', '🌶️'],
    ['Corn', '玉米', 'KORN', '🌽'],
    ['Spinach', '菠菜', 'SPIN-ij', '🥬'],
    ['Pumpkin', '南瓜', 'PUM-kin', '🎃'],
    ['Eggplant', '茄子', 'EG-plant', '🍆'],
    ['Garlic', '大蒜', 'GAR-lik', '🧄'],
    ['Mushroom', '蘑菇', 'MUSH-room', '🍄'],
    ['Celery', '芹菜', 'SEL-uh-ree', '🥬'],
    ['Radish', '萝卜', 'RAD-ish', '🥬'],
    ['Zucchini', '西葫芦', 'zoo-KEE-nee', '🥒'],
    ['Asparagus', '芦笋', 'uh-SPAR-uh-gus', '🥦'],
    ['Beet', '甜菜', 'BEET', '🟣'],
    ['Peas', '豌豆', 'PEEZ', '🟢'],
    ['Beans', '豆类', 'BEENZ', '🟤'],
    ['Cauliflower', '花菜', 'KO-luh-flow-er', '🥦'],
    ['Kale', '羽衣甘蓝', 'KAYL', '🥬'],
    ['Leek', '韭葱', 'LEEK', '🟢'],
    ['Chard', '牛皮菜', 'CHARD', '🥬'],
    ['Arugula', '芝麻菜', 'uh-ROO-guh-luh', '🥬'],
    ['Parsnip', '欧洲防风草', 'PAR-snip', '🟤'],
    ['Turnip', '芜菁', 'TER-nip', '🟤'],
    ['Squash', '南瓜', 'SKWOSH', '🎃'],
  ],
  Food: [
    ['Bread', '面包', 'BRED', '🍞'],
    ['Rice', '米饭', 'RYS', '🍚'],
    ['Pasta', '意大利面', 'PAHS-tuh', '🍝'],
    ['Pizza', '披萨', 'PEET-suh', '🍕'],
    ['Burger', '汉堡', 'BER-ger', '🍔'],
    ['Hot dog', '热狗', 'HOT DOG', '🌭'],
    ['Sandwich', '三明治', 'SAN-wich', '🥪'],
    ['Salad', '沙拉', 'SAL-ud', '🥗'],
    ['Soup', '汤', 'SOOP', '🍲'],
    ['Steak', '牛排', 'STAYK', '🥩'],
    ['Chicken', '鸡肉', 'CHIK-un', '🍗'],
    ['Fish', '鱼', 'FISH', '🐟'],
    ['Egg', '鸡蛋', 'EG', '🥚'],
    ['Cheese', '奶酪', 'CHEEZ', '🧀'],
    ['Milk', '牛奶', 'MILK', '🥛'],
    ['Yogurt', '酸奶', 'YO-gurt', '🥛'],
    ['Butter', '黄油', 'BUT-er', '🧈'],
    ['Honey', '蜂蜜', 'HUN-ee', '🍯'],
    ['Jam', '果酱', 'JAM', '🍓'],
    ['Chocolate', '巧克力', 'CHOK-lit', '🍫'],
    ['Candy', '糖果', 'KAN-dee', '🍬'],
    ['Cookie', '饼干', 'KUK-ee', '🍪'],
    ['Cake', '蛋糕', 'KAYK', '🎂'],
    ['Pie', '馅饼', 'PY', '🥧'],
    ['Ice cream', '冰淇淋', 'YS KREEM', '🍦'],
    ['Donut', '甜甜圈', 'DO-nut', '🍩'],
    ['Coffee', '咖啡', 'KAW-fee', '☕'],
    ['Tea', '茶', 'TEE', '🍵'],
    ['Juice', '果汁', 'JOO-S', '🧃'],
    ['Soda', '汽水', 'SO-duh', '🥤'],
  ],
  Animals: [
    ['Dog', '狗', 'DAWG', '🐕'],
    ['Cat', '猫', 'KAT', '🐈'],
    ['Bird', '鸟', 'BERD', '🐦'],
    ['Fish', '鱼', 'FISH', '🐠'],
    ['Lion', '狮子', 'LY-un', '🦁'],
    ['Tiger', '老虎', 'TY-ger', '🐯'],
    ['Elephant', '大象', 'EL-uh-funt', '🐘'],
    ['Monkey', '猴子', 'MUN-kee', '🐵'],
    ['Panda', '熊猫', 'PAN-duh', '🐼'],
    ['Bear', '熊', 'BAIR', '🐻'],
    ['Rabbit', '兔子', 'RAB-it', '🐰'],
    ['Fox', '狐狸', 'FOKS', '🦊'],
    ['Wolf', '狼', 'WULF', '🐺'],
    ['Deer', '鹿', 'DEER', '🦌'],
    ['Giraffe', '长颈鹿', 'juh-RAF', '🦒'],
    ['Zebra', '斑马', 'ZEE-bruh', '🦓'],
    ['Cow', '牛', 'KOW', '🐄'],
    ['Pig', '猪', 'PIG', '🐷'],
    ['Sheep', '羊', 'SHEEP', '🐑'],
    ['Horse', '马', 'HORS', '🐴'],
    ['Chicken', '鸡', 'CHIK-un', '🐔'],
    ['Duck', '鸭子', 'DUK', '🦆'],
    ['Penguin', '企鹅', 'PEN-gwin', '🐧'],
    ['Frog', '青蛙', 'FROG', '🐸'],
    ['Snake', '蛇', 'SNAYK', '🐍'],
    ['Turtle', '乌龟', 'TER-tul', '🐢'],
    ['Butterfly', '蝴蝶', 'BUT-er-fly', '🦋'],
    ['Bee', '蜜蜂', 'BEE', '🐝'],
    ['Spider', '蜘蛛', 'SPY-der', '🕷️'],
    ['Ant', '蚂蚁', 'ANT', '🐜'],
  ],
  Colors: [
    ['Red', '红色', 'RED', '🔴'],
    ['Blue', '蓝色', 'BLOO', '🔵'],
    ['Yellow', '黄色', 'YEL-o', '🟡'],
    ['Green', '绿色', 'GREEN', '🟢'],
    ['Orange', '橙色', 'OR-inj', '🟠'],
    ['Purple', '紫色', 'PER-pul', '🟣'],
    ['Pink', '粉红色', 'PINGK', '🩷'],
    ['Brown', '棕色', 'BROWN', '🟤'],
    ['Black', '黑色', 'BLAK', '⚫'],
    ['White', '白色', 'HWYT', '⚪'],
    ['Gray', '灰色', 'GRAY', '⚪'],
    ['Gold', '金色', 'GOLD', '🟡'],
    ['Silver', '银色', 'SIL-ver', '⚪'],
    ['Cyan', '青色', 'SY-an', '🔵'],
    ['Magenta', '洋红色', 'muh-JEN-tuh', '🟣'],
  ],
  Numbers: [
    ['One', '一', 'WUN', '1️⃣'],
    ['Two', '二', 'TOO', '2️⃣'],
    ['Three', '三', 'THREE', '3️⃣'],
    ['Four', '四', 'FOR', '4️⃣'],
    ['Five', '五', 'FYV', '5️⃣'],
    ['Six', '六', 'SIKS', '6️⃣'],
    ['Seven', '七', 'SEV-un', '7️⃣'],
    ['Eight', '八', 'AYT', '8️⃣'],
    ['Nine', '九', 'NYN', '9️⃣'],
    ['Ten', '十', 'TEN', '🔟'],
    ['Eleven', '十一', 'uh-LEV-un', '1️⃣1️⃣'],
    ['Twelve', '十二', 'TWELV', '1️⃣2️⃣'],
    ['Twenty', '二十', 'TWEN-tee', '2️⃣0️⃣'],
    ['Thirty', '三十', 'THER-tee', '3️⃣0️⃣'],
    ['Forty', '四十', 'FOR-tee', '4️⃣0️⃣'],
    ['Fifty', '五十', 'FIF-tee', '5️⃣0️⃣'],
    ['Sixty', '六十', 'SIK-stee', '6️⃣0️⃣'],
    ['Seventy', '七十', 'SEV-un-tee', '7️⃣0️⃣'],
    ['Eighty', '八十', 'AY-tee', '8️⃣0️⃣'],
    ['Ninety', '九十', 'NY-nuh-tee', '9️⃣0️⃣'],
    ['Hundred', '一百', 'HUN-dred', '💯'],
    ['Thousand', '一千', 'THOU-zund', '💰'],
    ['Million', '一百万', 'MIL-yun', '💰'],
    ['Zero', '零', 'ZEER-o', '0️⃣'],
    ['Plus', '加', 'PLUS', '➕'],
  ],
  Body: [
    ['Head', '头', 'HED', '🗣️'],
    ['Hair', '头发', 'HAIR', '💇'],
    ['Face', '脸', 'FAYS', '😊'],
    ['Eye', '眼睛', 'Y', '👁️'],
    ['Nose', '鼻子', 'NOZ', '👃'],
    ['Mouth', '嘴', 'MOUTH', '👄'],
    ['Ear', '耳朵', 'EER', '👂'],
    ['Tooth', '牙齿', 'TOOTH', '🦷'],
    ['Tongue', '舌头', 'TUNG', '👅'],
    ['Neck', '脖子', 'NEK', '🪡'],
    ['Shoulder', '肩膀', 'SHOL-der', '💪'],
    ['Arm', '胳膊', 'ARM', '💪'],
    ['Hand', '手', 'HAND', '🤚'],
    ['Finger', '手指', 'FING-ger', '👆'],
    ['Thumb', '大拇指', 'THUM', '👍'],
    ['Chest', '胸部', 'CHEST', '💓'],
    ['Heart', '心脏', 'HART', '❤️'],
    ['Stomach', '胃', 'STUM-uk', '🤢'],
    ['Back', '背', 'BAK', '🔙'],
    ['Leg', '腿', 'LEG', '🦵'],
    ['Knee', '膝盖', 'NEE', '🦵'],
    ['Foot', '脚', 'FUT', '🦶'],
    ['Toe', '脚趾', 'TO', '🦶'],
    ['Skin', '皮肤', 'SKIN', '🟤'],
    ['Bone', '骨头', 'BON', '🦴'],
    ['Muscle', '肌肉', 'MUS-ul', '💪'],
  ],
  School: [
    ['School', '学校', 'SKOOL', '🏫'],
    ['Teacher', '老师', 'TEECH-er', '👨‍🏫'],
    ['Student', '学生', 'STOO-dent', '👨‍🎓'],
    ['Classroom', '教室', 'KLAS-room', '🏫'],
    ['Desk', '课桌', 'DESK', '📚'],
    ['Chair', '椅子', 'CHAIR', '🪑'],
    ['Blackboard', '黑板', 'BLAK-bord', '🖊️'],
    ['Chalk', '粉笔', 'CHAWK', '🖍️'],
    ['Pencil', '铅笔', 'PEN-sul', '✏️'],
    ['Pen', '笔', 'PEN', '🖊️'],
    ['Paper', '纸', 'PAY-per', '📄'],
    ['Book', '书', 'BOOK', '📖'],
    ['Notebook', '笔记本', 'NOTE-book', '📓'],
    ['Backpack', '背包', 'BAK-pak', '🎒'],
    ['Bag', '包', 'BAG', '👜'],
    ['Ruler', '尺子', 'ROO-ler', '📏'],
    ['Eraser', '橡皮擦', 'ih-RAY-zer', '🧹'],
    ['Scissors', '剪刀', 'SIZ-erz', '✂️'],
    ['Glue', '胶水', 'GLOO', '🧴'],
    ['Tape', '胶带', 'TAYP', '📦'],
    ['Math', '数学', 'MATH', '🔢'],
    ['English', '英语', 'ING-lish', '🔤'],
    ['Science', '科学', 'SY-uns', '🔬'],
    ['Art', '艺术', 'ART', '🎨'],
    ['Music', '音乐', 'MYOO-zik', '🎵'],
    ['Physical Education', '体育', 'FIZ-i-kul ED-yuh-kay-shun', '⚽'],
  ],
  Nature: [
    ['Tree', '树', 'TREE', '🌳'],
    ['Flower', '花', 'FLOW-er', '🌸'],
    ['Grass', '草', 'GRAS', '🌱'],
    ['Mountain', '山', 'MOUN-tin', '⛰️'],
    ['River', '河', 'RIV-er', '🌊'],
    ['Lake', '湖', 'LAYK', '🏞️'],
    ['Ocean', '海洋', 'O-shun', '🌊'],
    ['Beach', '海滩', 'BEECH', '🏖️'],
    ['Forest', '森林', 'FOR-ist', '🌲'],
    ['Desert', '沙漠', 'DEZ-ert', '🏜️'],
    ['Sun', '太阳', 'SUN', '☀️'],
    ['Moon', '月亮', 'MOON', '🌙'],
    ['Star', '星星', 'STAR', '⭐'],
    ['Cloud', '云', 'KLOUD', '☁️'],
    ['Rain', '雨', 'RAYN', '🌧️'],
    ['Snow', '雪', 'SNO', '❄️'],
    ['Wind', '风', 'WIND', '💨'],
    ['Rainbow', '彩虹', 'RAYN-bo', '🌈'],
    ['Lightning', '闪电', 'LYT-ning', '⚡'],
    ['Thunder', '雷', 'THUN-der', '⛈️'],
    ['Leaf', '叶子', 'LEAF', '🍃'],
    ['Branch', '树枝', 'BRANCH', '🌿'],
    ['Root', '根', 'ROOT', '🌾'],
    ['Seed', '种子', 'SEED', '🌱'],
    ['Soil', '土壤', 'SOYL', '🟤'],
    ['Rock', '岩石', 'ROK', '🪨'],
  ],
  Weather: [
    ['Sunny', '晴天', 'SUN-ee', '☀️'],
    ['Cloudy', '多云', 'KLOU-dee', '☁️'],
    ['Rainy', '下雨', 'RAY-nee', '🌧️'],
    ['Snowy', '下雪', 'SNO-ee', '❄️'],
    ['Windy', '有风', 'WIN-dee', '💨'],
    ['Hot', '热', 'HOT', '🔥'],
    ['Cold', '冷', 'KOLD', '❄️'],
    ['Warm', '温暖', 'WORM', '🌡️'],
    ['Cool', '凉爽', 'KOOL', '😎'],
    ['Foggy', '有雾', 'FOG-ee', '🌫️'],
    ['Stormy', '暴风雨', 'STOR-mee', '⛈️'],
    ['Hail', '冰雹', 'HAYL', '🧊'],
    ['Frost', '霜', 'FROST', '❄️'],
    ['Dew', '露水', 'DOO', '💧'],
    ['Humidity', '湿度', 'hyoo-MID-i-tee', '💧'],
    ['Pressure', '气压', 'PRESH-er', '🌡️'],
    ['Temperature', '温度', 'TEM-pur-uh-chur', '🌡️'],
    ['Forecast', '天气预报', 'FOR-kast', '📡'],
    ['Season', '季节', 'SEE-zun', '🍂'],
    ['Spring', '春天', 'SPRING', '🌸'],
    ['Summer', '夏天', 'SUM-er', '☀️'],
    ['Fall', '秋天', 'FAWL', '🍂'],
    ['Winter', '冬天', 'WIN-ter', '❄️'],
    ['Tornado', '龙卷风', 'tor-NAY-do', '🌪️'],
    ['Hurricane', '飓风', 'HER-i-kayn', '🌀'],
    ['Earthquake', '地震', 'ERTH-kwayk', '🌍'],
  ],
  Sports: [
    ['Soccer', '足球', 'SOK-er', '⚽'],
    ['Basketball', '篮球', 'BAS-kit-bawl', '🏀'],
    ['Baseball', '棒球', 'BAS-bawl', '⚾'],
    ['Tennis', '网球', 'TEN-is', '🎾'],
    ['Volleyball', '排球', 'VOL-ee-bawl', '🏐'],
    ['Swimming', '游泳', 'SWIM-ing', '🏊'],
    ['Running', '跑步', 'RUN-ning', '🏃'],
    ['Cycling', '骑自行车', 'SY-kling', '🚴'],
    ['Skating', '滑冰', 'SKAY-ting', '⛸️'],
    ['Skiing', '滑雪', 'SKEE-ing', '⛷️'],
    ['Surfing', '冲浪', 'SER-fing', '🏄'],
    ['Bowling', '保龄球', 'BO-ling', '🎳'],
    ['Golf', '高尔夫', 'GOLF', '⛳'],
    ['Badminton', '羽毛球', 'BAD-min-tun', '🏸'],
    ['Ping pong', '乒乓球', 'PING PONG', '🏓'],
    ['Boxing', '拳击', 'BOK-sing', '🥊'],
    ['Wrestling', '摔跤', 'RES-ling', '🤼'],
    ['Gymnastics', '体操', 'jim-NAS-tiks', '🤸'],
    ['Yoga', '瑜伽', 'YO-guh', '🧘'],
    ['Martial arts', '武术', 'MAR-shul ARTS', '🥋'],
    ['Archery', '射箭', 'AR-cher-ee', '🏹'],
    ['Climbing', '攀岩', 'KLY-ming', '🧗'],
    ['Hiking', '徒步旅行', 'HY-king', '🥾'],
    ['Fishing', '钓鱼', 'FISH-ing', '🎣'],
    ['Hunting', '狩猎', 'HUN-ting', '🔫'],
    ['Dancing', '跳舞', 'DAN-sing', '💃'],
  ],
  Transportation: [
    ['Car', '汽车', 'KAR', '🚗'],
    ['Bus', '公交车', 'BUS', '🚌'],
    ['Train', '火车', 'TRAYN', '🚂'],
    ['Airplane', '飞机', 'AIR-playn', '✈️'],
    ['Bicycle', '自行车', 'BY-sik-ul', '🚲'],
    ['Motorcycle', '摩托车', 'MO-tor-sy-kul', '🏍️'],
    ['Boat', '船', 'BOT', '⛵'],
    ['Ship', '轮船', 'SHIP', '🚢'],
    ['Helicopter', '直升机', 'HEL-i-kop-ter', '🚁'],
    ['Rocket', '火箭', 'ROK-it', '🚀'],
    ['Truck', '卡车', 'TRUK', '🚚'],
    ['Taxi', '出租车', 'TAK-see', '🚕'],
    ['Ambulance', '救护车', 'AM-byuh-luns', '🚑'],
    ['Fire truck', '消防车', 'FY-er TRUK', '🚒'],
    ['Police car', '警车', 'puh-LEES KAR', '🚓'],
    ['Subway', '地铁', 'SUB-way', '🚇'],
    ['Tram', '电车', 'TRAM', '🚊'],
    ['Scooter', '滑板车', 'SKOO-ter', '🛴'],
    ['Skateboard', '滑板', 'SKAYT-bord', '🛹'],
    ['Roller skates', '轮滑鞋', 'RO-ler SKYTS', '🛼'],
    ['Canoe', '独木舟', 'kuh-NOO', '🛶'],
    ['Kayak', '皮划艇', 'KY-ak', '🛶'],
    ['Cruise ship', '游轮', 'KROOS SHIP', '🚢'],
    ['Gondola', '贡多拉', 'GON-duh-luh', '🚣'],
    ['Sleigh', '雪橇', 'SLAY', '🛷'],
    ['Hot air balloon', '热气球', 'HOT AIR buh-LOON', '🎈'],
  ],
  Technology: [
    ['Computer', '电脑', 'kum-PYOO-ter', '💻'],
    ['Phone', '电话', 'FON', '☎️'],
    ['Smartphone', '智能手机', 'SMART-fon', '📱'],
    ['Tablet', '平板电脑', 'TAB-lit', '📱'],
    ['Television', '电视', 'TEL-uh-vizh-un', '📺'],
    ['Radio', '收音机', 'RAY-dee-o', '📻'],
    ['Camera', '相机', 'KAM-er-uh', '📷'],
    ['Video camera', '摄像机', 'VID-ee-o KAM-er-uh', '📹'],
    ['Microphone', '麦克风', 'MY-kro-fon', '🎤'],
    ['Speaker', '扬声器', 'SPEAK-er', '🔊'],
    ['Headphones', '耳机', 'HED-fonz', '🎧'],
    ['Keyboard', '键盘', 'KEE-bord', '⌨️'],
    ['Mouse', '鼠标', 'MOUS', '🖱️'],
    ['Monitor', '显示器', 'MON-i-ter', '🖥️'],
    ['Printer', '打印机', 'PRIN-ter', '🖨️'],
    ['Scanner', '扫描仪', 'SKAN-er', '📠'],
    ['Router', '路由器', 'ROO-ter', '📡'],
    ['Modem', '调制解调器', 'MO-dem', '📡'],
    ['USB drive', 'USB驱动器', 'YOO-ES-BEE DRYV', '💾'],
    ['Hard drive', '硬盘', 'HARD DRYV', '💾'],
    ['Battery', '电池', 'BAT-uh-ree', '🔋'],
    ['Charger', '充电器', 'CHAR-jer', '🔌'],
    ['Cable', '电缆', 'KAY-bul', '🔌'],
    ['Wire', '电线', 'WYR', '⚡'],
    ['Satellite', '卫星', 'SAT-uh-lyt', '🛰️'],
    ['Drone', '无人机', 'DRON', '🚁'],
  ],
  Clothes: [
    ['Shirt', '衬衫', 'SHERT', '👔'],
    ['T-shirt', 'T恤', 'TEE-SHERT', '👕'],
    ['Pants', '裤子', 'PANTS', '👖'],
    ['Dress', '连衣裙', 'DRES', '👗'],
    ['Skirt', '裙子', 'SKERT', '👗'],
    ['Jacket', '夹克', 'JAK-it', '🧥'],
    ['Coat', '外套', 'KOT', '🧥'],
    ['Sweater', '毛衣', 'SWET-er', '🧶'],
    ['Hoodie', '连帽衫', 'HU-dee', '🧥'],
    ['Vest', '背心', 'VEST', '🦺'],
    ['Hat', '帽子', 'HAT', '🎩'],
    ['Cap', '鸭舌帽', 'KAP', '🧢'],
    ['Scarf', '围巾', 'SKARF', '🧣'],
    ['Gloves', '手套', 'GLUVZ', '🧤'],
    ['Socks', '袜子', 'SOKS', '🧦'],
    ['Shoe', '鞋', 'SHOO', '👞'],
    ['Sneaker', '运动鞋', 'SNEE-ker', '👟'],
    ['Boot', '靴子', 'BOOT', '🥾'],
    ['Sandal', '凉鞋', 'SAN-dul', '👡'],
    ['Flip flop', '拖鞋', 'FLIP FLOP', '👡'],
    ['Belt', '皮带', 'BELT', '🪡'],
    ['Tie', '领带', 'TY', '👔'],
    ['Bow tie', '蝴蝶结领带', 'BO TY', '🎀'],
    ['Pocket', '口袋', 'POK-it', '👖'],
    ['Button', '纽扣', 'BUT-un', '⭕'],
    ['Zipper', '拉链', 'ZIP-er', '🔐'],
  ],
  House: [
    ['House', '房子', 'HOUS', '🏠'],
    ['Kitchen', '厨房', 'KICH-un', '🍳'],
    ['Bedroom', '卧室', 'BED-room', '🛏️'],
    ['Bathroom', '浴室', 'BATH-room', '🚿'],
    ['Living room', '客厅', 'LIV-ing ROOM', '🛋️'],
    ['Dining room', '餐厅', 'DY-ning ROOM', '🍽️'],
    ['Hallway', '走廊', 'HAHL-way', '🚪'],
    ['Stairs', '楼梯', 'STAIRZ', '🪜'],
    ['Wall', '墙壁', 'WAWL', '🧱'],
    ['Roof', '屋顶', 'ROOF', '🏠'],
    ['Floor', '地板', 'FLOR', '🟫'],
    ['Ceiling', '天花板', 'SEE-ling', '⬜'],
    ['Door', '门', 'DOR', '🚪'],
    ['Window', '窗户', 'WIN-do', '🪟'],
    ['Bed', '床', 'BED', '🛏️'],
    ['Sofa', '沙发', 'SO-fuh', '🛋️'],
    ['Table', '桌子', 'TAY-bul', '🪑'],
    ['Chair', '椅子', 'CHAIR', '🪑'],
    ['Lamp', '台灯', 'LAMP', '💡'],
    ['Refrigerator', '冰箱', 'rih-FRIJ-uh-ray-ter', '🧊'],
    ['Stove', '炉子', 'STOV', '🔥'],
    ['Sink', '水槽', 'SINGK', '🚰'],
    ['Toilet', '马桶', 'TOY-lit', '🚽'],
    ['Shower', '淋浴', 'SHOW-er', '🚿'],
    ['Bathtub', '浴缸', 'BATH-tub', '🛁'],
    ['Mirror', '镜子', 'MIR-er', '🪞'],
    ['Cabinet', '橱柜', 'KAB-uh-nit', '🗄️'],
    ['Drawer', '抽屉', 'DROR', '🗄️'],
    ['Closet', '衣柜', 'KLOZ-it', '🚪'],
    ['Bookshelf', '书架', 'BOOK-shelf', '📚'],
  ],
  Places: [
    ['Park', '公园', 'PARK', '🌳'],
    ['School', '学校', 'SKOOL', '🏫'],
    ['Library', '图书馆', 'LY-brer-ee', '📚'],
    ['Hospital', '医院', 'HOS-pit-ul', '🏥'],
    ['Restaurant', '餐厅', 'RES-tuh-rahnt', '🍽️'],
    ['Supermarket', '超市', 'SOO-per-mar-kit', '🛒'],
    ['Bank', '银行', 'BANGK', '🏦'],
    ['Post office', '邮局', 'POST AW-fis', '📮'],
    ['Airport', '机场', 'AIR-port', '✈️'],
    ['Train station', '火车站', 'TRAYN STAY-shun', '🚂'],
    ['Beach', '海滩', 'BEECH', '🏖️'],
    ['Mountain', '山', 'MOUN-tin', '⛰️'],
    ['River', '河', 'RIV-er', '🌊'],
    ['Lake', '湖', 'LAYK', '🏞️'],
    ['Forest', '森林', 'FOR-ist', '🌲'],
    ['Desert', '沙漠', 'DEZ-ert', '🏜️'],
    ['City', '城市', 'SIT-ee', '🏙️'],
    ['Village', '村庄', 'VIL-ij', '🏘️'],
    ['Farm', '农场', 'FARM', '🚜'],
    ['Garden', '花园', 'GAR-den', '🌻'],
    ['Zoo', '动物园', 'ZOO', '🦁'],
    ['Museum', '博物馆', 'myoo-ZEE-um', '🖼️'],
    ['Theater', '剧院', 'THEE-uh-ter', '🎭'],
    ['Cinema', '电影院', 'SIN-uh-muh', '🎬'],
    ['Market', '市场', 'MAR-kit', '🛍️'],
    ['Temple', '寺庙', 'TEM-pul', '🏯'],
    ['Church', '教堂', 'CHURCH', '⛪'],
    ['Mosque', '清真寺', 'MOSK', '🕌'],
    ['Gym', '健身房', 'JIM', '🏋️'],
    ['Swimming pool', '游泳池', 'SWIM-ing POOL', '🏊'],
  ],
  Objects: [
    ['Book', '书', 'BOOK', '📖'],
    ['Pen', '笔', 'PEN', '🖊️'],
    ['Pencil', '铅笔', 'PEN-sul', '✏️'],
    ['Paper', '纸', 'PAY-per', '📄'],
    ['Notebook', '笔记本', 'NOTE-book', '📓'],
    ['Backpack', '背包', 'BAK-pak', '🎒'],
    ['Bag', '包', 'BAG', '👜'],
    ['Wallet', '钱包', 'WAL-it', '👛'],
    ['Key', '钥匙', 'KEY', '🔑'],
    ['Lock', '锁', 'LOK', '🔒'],
    ['Door', '门', 'DOR', '🚪'],
    ['Window', '窗户', 'WIN-do', '🪟'],
    ['Clock', '钟', 'KLOK', '🕐'],
    ['Watch', '手表', 'WOCH', '⌚'],
    ['Camera', '相机', 'KAM-er-uh', '📷'],
    ['Phone', '电话', 'FON', '📱'],
    ['Computer', '电脑', 'kum-PYOO-ter', '💻'],
    ['Television', '电视', 'TEL-uh-vizh-un', '📺'],
    ['Radio', '收音机', 'RAY-dee-o', '📻'],
    ['Headphones', '耳机', 'HED-fonz', '🎧'],
    ['Speaker', '扬声器', 'SPEAK-er', '🔊'],
    ['Microphone', '麦克风', 'MY-kro-fon', '🎤'],
    ['Lamp', '台灯', 'LAMP', '💡'],
    ['Candle', '蜡烛', 'KAN-dul', '🕯️'],
    ['Flashlight', '手电筒', 'FLASH-lyt', '🔦'],
    ['Umbrella', '雨伞', 'um-BREL-uh', '☂️'],
    ['Hat', '帽子', 'HAT', '🎩'],
    ['Shoe', '鞋', 'SHOO', '👞'],
    ['Glasses', '眼镜', 'GLAS-iz', '👓'],
    ['Toy', '玩具', 'TOY', '🎮'],
  ],
};

export function generateWords(): Word[] {
  const words: Word[] = [];
  let id = 1;

  for (const [category, wordList] of Object.entries(wordCategories)) {
    for (const [english, chinese, pronunciation, emoji] of wordList) {
      words.push({
        id,
        english,
        chinese,
        pronunciation,
        category,
        emoji,
      });
      id++;
    }
  }

  return words;
}
